= Software Download 

There are three types of download commands described in this section:

* Generic file download
* Helm chart download
* Docker image download

== 1.1 Generic file download 

The generic file download is completed using the wget command.

===   1. Run the following wget command: 

wget --http-user=PAT --ask-password https://<swdp download site>/artifactory/<product-name>-Product/<file-path>  

* The --HTTP-user option is used to specify the username for HTTP authentication, which is a static value PAT (personal access token).

* The --ask-password option prompts the user to enter a token for authentication.

===   2. Enter the token to proceed with the download: 

Example:

End customer downloading a file for Altiplano Access Controller:

$ wget --http-user=PAT --ask-password https://swdp-fi.support.nokia.com/artifactory/Altiplano-Access-Controller-Product/21.6.2/21.6.2/INSTALL_MEDIA/product.txt

== 1.2 Helm chart download

The Helm chart download must be started with the helm repo command. Once this command is entered, then other helm commands can be used. Following is the format for the helm repo command: 

helm repo add <reponame> <hostname>/artifactory/<product-name>-Helm --username PAT --password <token> --pass-credentials

Example: 

helm repo add altiplano https://swdp-fi.support.nokia.com/artifactory/Altiplano-Access-Controller-Product-Helm --username PAT --password <token> --pass-credentials

After that, the regular helm commands will work:

helm search repo altiplano-infra –versions –devel

helm pull aprepo/altiplano-infra --version 21.12.1-REL-0216

helm pull fmcrepo/altiplano-infra --version 21.12.1-REL-0216

== 1.3 Docker image download

Run the following command to log in to Docker:

docker login https://<product name>-docker.<hostname> -u PAT

Example:

docker login https://altiplano-access-controller-product-docker.swdp-fi.support.nokia.com -u PAT 

After logging in, enter the access token, when prompted. 

After that, the regular docker commands will work:

docker pull altiplano-access-controller-product-docker.swdp-fi.support.nokia.com/anv:21.12.1-REL_251

docker pull altiplano-fastmile-controller-product-docker.swdp-fi.support.nokia.com/anv:21.12.1-REL_251

